server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
            - id: auction-service
              uri: lb://auction-service
              predicates:
                - Path=/ws/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            add-to-simple-url-handler-mapping: true
            corsConfigurations:
              '[/**]':
                allowedOriginPatterns:
                  - "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: Auth Service
        url: http://localhost:8000/auth-service/v3/api-docs

jwt:
  secret: dXNlcjEtc2VjcmV0LWtleS1mb3ItZ2F0ZXdheS1wcm9qZWN0LWV4YW1wbGU=
  access-token-expiration-time: 360000
