server:
  port: 8081

spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  access-token:
    secret: realbid-jwt-access-token-secret-key-for-hs256-algorithm-must-be-at-least-32bytes
    expiration-seconds: 3600 # 1시간

  refresh-token:
    secret: realbid-jwt-refresh-token-secret-key-for-hs256-algorithm-must-be-at-least-32bytes
    expiration-seconds: 1209600 # 14일